# Generated by Django 3.2.9 on 2023-05-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_system', '0003_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('admin_pwd', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
