# Generated by Django 3.2.9 on 2023-05-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_system', '0005_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='admin',
        ),
    ]
