# Generated by Django 3.2.9 on 2023-05-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_system', '0009_bossinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('count', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='头像路径')),
            ],
        ),
    ]
