# Generated by Django 4.2.6 on 2023-10-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_system', '0010_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.FileField(max_length=128, upload_to='city/', verbose_name='图片路径'),
        ),
    ]
